### ISSUE TITLE
Can't install new packages in anaconda

### ISSUE THREAD

**Issue by shyamiitk** [Anaconda-Platform/support#119]
INFO conda.common.io:captured(27): overtaking stderr and stdout
INFO conda.common.io:captured(33): stderr and stdout yielded back
Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Users\H191093\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:\Users\H191093\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\H191093\AppData\Local\Continuum\Anaconda3\envs
          package cache : C:\Users\H191093\AppData\Local\Continuum\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/r/win-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/defaultsh/win-64
                          https://conda.anaconda.org/defaultsh/noarch
            config file : C:\Users\H191093\.condarc
           offline mode : False

`$ C:\Users\H191093\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py install channelpackage -c mychannel -vv`

    Traceback (most recent call last):
      File "C:\Users\H191093\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 120, in fetch_repodata
        resp.raise_for_status()
      File "C:\Users\H191093\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\models.py", line 893, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/mychannel/win-64/repodata.json
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Users\H191093\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\H191093\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\H191093\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\H191093\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Users\H191093\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\H191093\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\H191093\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\H191093\AppData\Local\Continuum\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "C:\Users\H191093\AppData\Local\Continuum\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "C:\Users\H191093\AppData\Local\Continuum\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\H191093\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "C:\Users\H191093\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 223, in fetch_repodata
        e.response.reason if e.response else None)
    conda.exceptions.CondaHTTPError: HTTP 404 None
    for url <None>
    
    The remote server could not find the channel you requested.
    
    You will need to adjust your conda configuration to proceed.
    Use `conda config --show` to view your configuration's current state.
    Further configuration help can be found at <http://conda.pydata.org/docs/config.html>.

**Comment by koverholt** [comment]
Closing as stale / transient. In the future, bugs or enhancement requests for Anaconda Cloud can be submitted at https://www.anaconda.com/contact-us/ if this issue occurs again.
