### ISSUE TITLE
Anaconda install leaves matplotlib.pyplot with `ImportError: No module named _common` error

### ISSUE THREAD

**Issue by gallamine** [Anaconda-Platform/support#91]
I'm running conda version `conda 4.2.13` in OSX 10.10.5

My environment.yml file is:

```
name: conda_test
dependencies:
- python=2.7
- anaconda
```

I do:

```
$ conda env create
$ source activate conda_test
$ python
Python 2.7.12 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:43:17)
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/william/anaconda/envs/conda_test/lib/python2.7/site-packages/matplotlib/pyplot.py", line 36, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/Users/william/anaconda/envs/conda_test/lib/python2.7/site-packages/matplotlib/figure.py", line 40, in <module>
    from matplotlib.axes import Axes, SubplotBase, subplot_class_factory
  File "/Users/william/anaconda/envs/conda_test/lib/python2.7/site-packages/matplotlib/axes/__init__.py", line 4, in <module>
    from ._subplots import *
  File "/Users/william/anaconda/envs/conda_test/lib/python2.7/site-packages/matplotlib/axes/_subplots.py", line 10, in <module>
    from matplotlib.axes._axes import Axes
  File "/Users/william/anaconda/envs/conda_test/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 23, in <module>
    import matplotlib.dates as _  # <-registers a date unit converter
  File "/Users/william/anaconda/envs/conda_test/lib/python2.7/site-packages/matplotlib/dates.py", line 126, in <module>
    from dateutil.rrule import (rrule, MO, TU, WE, TH, FR, SA, SU, YEARLY,
  File "/Users/william/anaconda/envs/conda_test/lib/python2.7/site-packages/dateutil/rrule.py", line 22, in <module>
    from ._common import weekday as weekdaybase
ImportError: No module named _common
```

I haven't found any way around this.

If I remove `anaconda` from the environment file and only install `matplotlib` it will work, but otherwise I continue to get this error.

**Comment by kilojoules** [comment]
+1 I have the same error from `conda create -n fenicstest -c conda-forge python=2.7 fenics=2016.1 dolfin-adjoint=2016.1`

**Comment by koverholt** [comment]
This does not appear to be an issue with Anaconda Cloud. Issues related to Anaconda or Conda can be reported in the corresponding Github issue tracker: https://anaconda.org/contact/report.
